server:
  port: 9090

spring:
  profiles:
    active:
      - local
  jpa:
    hibernate:
      ddl-auto:
        - update

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/test
    username:
    password:
    driver-class-name: org.h2.Driver